language: android

jdk:
  - oraclejdk8

sudo: false

android:
  components:
    - tools
    - android-25
    - build-tools-25.0.2
    - extra-android-m2repository

cache: false

install:
  # Ensure Gradle wrapper is executable, download wrapper and show version
  - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v
  # Download and show android dependencies
  # - ./gradlew androidDependencies

script:
  - ./gradlew clean build -Pbuild=dev
